config/routes.rb
SILBApp::Application.routes.draw do

  get "errors/show"

  get "customers/index"

  root to: 'static_pages#home'

  resources :users,            only: [:new, :create, :edit, :update]
  resources :sessions,         only: [:new, :create, :destroy]
  resources :password_resets
  resources :user_activations, only: [:edit]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'static_pages#contact'

  resources :products, only: [:index, :show]
  match '/catalog', to: 'products#index'

  resources :orders, only: [:index]
  match '/shopping_cart', to: 'orders#show'
  resources :line_items,  only: [:create, :destroy, :update]

  resources :shipping_addresses,  only: [:new, :create]
  match '/checkout', to: 'shipping_addresses#new'

  resources :shipping_costs,  only: [:index]

  resources :order_payments, only: [:new, :create]
  match '/express',       to: 'order_payments#express'
  match '/paypal_cancel', to: 'order_payments#paypal_cancel'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :users,                  only: [:index, :new, :create, :edit, :update, :destroy]

    resources :regions,                only: [:index, :new, :create, :edit, :update]
    resources :region_states,          only: [:update]

    resources :cities,                 only: [:index, :new, :create, :edit, :update]
    resources :city_states,            only: [:update]

    resources :shipping_methods,       only: [:index, :new, :create, :edit, :update]
    resources :shipping_method_states, only: [:update]

    resources :shipping_costs,         only: [:index, :new, :create, :edit, :update]
    resources :shipping_cost_states,   only: [:update]

    resources :categories,             only: [:index, :new, :create, :edit, :update, :destroy]

    resources :brands,                 only: [:index, :new, :create, :edit, :update]
    resources :brand_states,           only: [:update]

    resources :products,               only: [:index, :show, :new, :create, :edit, :update]
    resources :product_states,         only: [:update]

    resources :pictures,               only: [:index, :create, :destroy]

    resources :orders,                 only: [:index, :show, :update]

    resources :customers,              only: [:index]

    # get '/sales_report', to: 'reports#sales_report'
    match '/sales_report', to: 'reports#sales_report', via: [:post, :get]

  end

  match 'errors/:status', to: 'errors#show', constraints: {status: /\d{3}/} #,  via: :all
  match '/:status', to: 'errors#show', constraints: {status: /\d{3}/} #,  via: :all

end

app/views/layouts/admin/menu/_content.html.erb
<li><%= link_to t('content'),     '#' %></li>

app/views/layouts/admin/menu/_customers.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t('customers') %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t('orders_list'),    admin_orders_path %></li>
    <li class="divider"></li>
    <li><%= link_to t('customers_list'), admin_customers_path   %></li>
  </ul>
</li>

app/views/layouts/admin/menu/_maintenance.html.erb
<% if( can?(:manage, Region) ||
       can?(:manage, City)   ||
       can?(:manage, ShippingMethod) ||
       can?(:manage, ShippingCost))
%>
  <li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('maintenance') %> <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <% if can?(:manage, Region) %>
        <li><%= link_to t('new_region'),             new_admin_region_path %></li>
        <li><%= link_to t('regions_list'),           admin_regions_path    %></li>
        <li class="divider"></li>
      <% end %>
      <% if can?(:manage, City) %>
        <li><%= link_to t('new_city'),               new_admin_city_path %></li>
        <li><%= link_to t('cities_list'),            admin_cities_path   %></li>
        <li class="divider"></li>
      <% end %>
      <% if can?(:manage, ShippingMethod) %>
        <li><%= link_to t('new_shipping_method'),    new_admin_shipping_method_path %></li>
        <li><%= link_to t('shipping_methods_list'),  admin_shipping_methods_path %></li>
      <% end %>
    </ul>
</li>
<% end %>

app/views/layouts/admin/menu/_products.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t('products') %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t('new_product'),     new_admin_product_path %></li>
    <li><%= link_to t('products_list'),   admin_products_path %></li>
    <li class="divider"></li>
    <li><%= link_to t('new_category'),    new_admin_category_path %></li>
    <li><%= link_to t('categories_list'), admin_categories_path   %></li>
    <li class="divider"></li>
    <li><%= link_to t('new_brand'),       new_admin_brand_path %></li>
    <li><%= link_to t('brands_list'),     admin_brands_path   %></li>
  </ul>
</li>

app/views/layouts/admin/menu/_reports.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t('reports') %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t('sales_report'), admin_sales_report_path %></li>
  </ul>
</li>

app/views/layouts/admin/menu/_users.html.erb
<% if can? :manage, User %>
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t('users') %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to t('new_user'),   new_admin_user_path %></li>
    <li><%= link_to t('users_list'), admin_users_path    %></li>
  </ul>
</li>
<% end %>