config/routes.rb
SILBApp::Application.routes.draw do

  get "errors/show"

  get "customers/index"

  root to: 'static_pages#home'

  resources :users,            only: [:new, :create, :edit, :update]
  resources :sessions,         only: [:new, :create, :destroy]
  resources :password_resets
  resources :user_activations, only: [:edit]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'static_pages#contact'

  resources :products, only: [:index, :show]
  match '/catalog', to: 'products#index'

  resources :orders, only: [:index]
  match '/shopping_cart', to: 'orders#show'
  resources :line_items,  only: [:create, :destroy, :update]

  resources :shipping_addresses,  only: [:new, :create]
  match '/checkout', to: 'shipping_addresses#new'

  resources :shipping_costs,  only: [:index]

  resources :order_payments, only: [:new, :create]
  match '/express',       to: 'order_payments#express'
  match '/paypal_cancel', to: 'order_payments#paypal_cancel'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :users,                  only: [:index, :new, :create, :edit, :update, :destroy]

    resources :regions,                only: [:index, :new, :create, :edit, :update]
    resources :region_states,          only: [:update]

    resources :cities,                 only: [:index, :new, :create, :edit, :update]
    resources :city_states,            only: [:update]

    resources :shipping_methods,       only: [:index, :new, :create, :edit, :update]
    resources :shipping_method_states, only: [:update]

    resources :shipping_costs,         only: [:index, :new, :create, :edit, :update]
    resources :shipping_cost_states,   only: [:update]

    resources :categories,             only: [:index, :new, :create, :edit, :update, :destroy]

    resources :brands,                 only: [:index, :new, :create, :edit, :update]
    resources :brand_states,           only: [:update]

    resources :products,               only: [:index, :show, :new, :create, :edit, :update]
    resources :product_states,         only: [:update]

    resources :pictures,               only: [:index, :create, :destroy]

    resources :orders,                 only: [:index, :show, :update]

    resources :customers,              only: [:index]

    # get '/sales_report', to: 'reports#sales_report'
    match '/sales_report', to: 'reports#sales_report', via: [:post, :get]

  end

  match 'errors/:status', to: 'errors#show', constraints: {status: /\d{3}/} #,  via: :all
  match '/:status', to: 'errors#show', constraints: {status: /\d{3}/} #,  via: :all

end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  state      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Brand < ActiveRecord::Base
  attr_accessible :name

  has_many :products
  has_many :pictures, :as => :imageable

  before_save { name.downcase! }

  validates :name,
    presence: true,
    length: { maximum: 50 },
    uniqueness: { case_sensitive: false }

  # State Machine
  state_machine :initial => :active do

    event :inactivate do
      transition :inactive => :inactive
      transition :active   => :inactive
    end

    event :activate do
      transition :inactive => :active
      transition :active   => :active
    end
  end

  def name
    read_attribute(:name).try(:titleize)
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::BaseController
  helper_method :sort_column, :sort_direction

  def index
    @brands = Brand.search(params[:search]).order(sort_column + " " + sort_direction)
        .paginate(per_page: 10, page: params[:page])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.create(params[:brand])
    if @brand.save
      params[:activate] ? @brand.activate! : @brand.inactivate!
      flash[:success] = t('brand_successfully_created')
      redirect_to admin_brands_path
    else
      render 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update_attributes(params[:brand])
      params[:activate] ? @brand.activate! : @brand.inactivate!
      flash[:success] = t('brand_successfully_updated')
      redirect_to admin_brands_path
    else
      render 'edit'
    end
  end

  private

    def sort_column
        Brand.column_names.include?(params[:sort].to_s) ? params[:sort] : "id"
    end

    def sort_direction
        %w(asc desc).include?(params[:direction].to_s) ? params[:direction] : "asc"
    end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_brand.html.erb
<tr>
    <td><%= brand.id %></td>
    <td><%= brand.name %></td>
    <td>
        <%= hidden_field_tag :hideen_state, brand.id, :id => "hidden-state-#{brand.id}" %>
        <%= check_box_tag :state, 1, brand.active?,   :id => "state-#{brand.id}" %>
    </td>
    <td><%= link_to t('edit'), edit_admin_brand_path(brand) %></td>
</tr>

app/views/admin/brands/_brands.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<% if @brands.any? %>
  <table class="table table-striped table-condensed" style="table-layout:fixed">
    <thead>
      <tr>
        <th style="width:10%"><%= sortable "id" %></th>
        <th style="width:40%"><%= sortable "name", t('activerecord.attributes.brand.name') %></th>
        <th style="width:10%"><%= t('activerecord.attributes.brand.state') %></th>
        <th style="width:40%"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @brands %>
    </tbody>
  </table>
  <%= will_paginate @brands, class: 'pagination pagination-centered' %>
<% else %>
  <%= content_tag( :div, class: "alert text-center" ) do %>
    <%= content_tag( :span, t('items_not_found') ) %>
  <% end %>
<% end %>

app/views/admin/brands/edit.html.erb
<% provide(:title, t('brand')) %>
<% provide(:section, t('brand')) %>

<div class="row">
  <div class="span12">
    <%= form_for [:admin, @brand], :validate => true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "span6" %>

      <%= label_tag :activate, nil, :class => 'checkbox' do %>
        <%= t('activerecord.attributes.brand.state') %>
        <%= check_box_tag :activate, 1, @brand.active? %>
      <% end %>
    </p>
      <%= f.submit t('update'), class: "btn btn-large btn-primary" %>
    <% end %>

    <h3><%= t('images') %></h3>
    <hr class="bs-docs-separator">
    <%= render 'shared/picture_upload', object: @brand %>

  </div>
</div>

app/views/admin/brands/index.html.erb
<% provide(:title, t('brands')) %>
<% provide(:section, t('brands')) %>

<%= form_tag admin_brands_path, method: 'get', id: "brands_search" do %>
  <div class="row">
    <div class="input-append span3">
      <%= label_tag :region_id, t('activerecord.attributes.brand.name') %>
      <%= text_field_tag :search, params[:search], :class => '' %>
      <%= submit_tag t('search'), class: 'btn' %>
    </div>
  </div>
  <hr class="bs-docs-separator">
  <div id="brands"><%= render 'brands' %></div>
<% end %>

app/views/admin/brands/index.js.erb
$('#brands').html("<%= escape_javascript(render("brands")) %>")

app/views/admin/brands/new.html.erb
<% provide(:title, t('new_brand')) %>
<% provide(:section, t('new_brand')) %>

<div class="row">
  <div class="span12">
    <%= form_for [:admin, @brand], :validate => true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "span6" %>

      <%= label_tag :activate, nil, :class => 'checkbox' do %>
        <%= t('activerecord.attributes.brand.state') %>
        <%= check_box_tag :activate, 1, true %>
      <% end %>
    </p>
      <%= f.submit t('save'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>